Reservation: refactorings, error still there.
Error is:
```
org.springframework.core.codec.DecodingException: JSON decoding error: Cannot construct instance of `com.rez.facility.resource.ResourceState` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)

Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.rez.facility.resource.ResourceState` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)

```